// This file is auto-generated by pnpm build:icons

export type IconNames =
  | "attachment-line"
  | "calendar-line"
  | "close-line"
  | "code-s-slash-line"
  | "github-line"
  | "linkedin-line"
  | "menu-line"
  | "timer-line";
